apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-crud-ingress-frontend0

  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # URL of your Git repository from Step 1
    repoURL: https://github.com/Sisay211219/ArgoCD.git
    targetRevision: HEAD
    # Path inside repo where manifests are located ('.' for root directory)
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
