apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-crud-app-frontend  
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # URL of the GitHub repo you just created
    repoURL: https://github.com/Sisay211219/ArgoCD.git
    targetRevision: HEAD
    # Path inside the repository where your YAML files are located
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
